# Generated by Django 3.2.16 on 2022-12-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class1_Grade',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('st_id', models.CharField(max_length=32, verbose_name='学生学号')),
                ('st_class', models.CharField(max_length=32, verbose_name='学生班级')),
                ('st_name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('cl1_grade', models.FloatField(verbose_name='总评成绩')),
                ('cl1_class', models.CharField(max_length=32, verbose_name='奖学金等第')),
            ],
            options={
                'db_table': 'class1_grade',
            },
        ),
        migrations.CreateModel(
            name='Class2_Grade',
            fields=[
                ('id2', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('st_id', models.CharField(max_length=32, verbose_name='学生学号')),
                ('co_st_type', models.IntegerField(verbose_name='综测类型')),
                ('st_name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('st_class', models.CharField(max_length=32, verbose_name='学生班级')),
                ('cl2_grade', models.FloatField(verbose_name='二级成绩')),
            ],
            options={
                'db_table': 'class2_grade',
            },
        ),
        migrations.CreateModel(
            name='Class3_Grade',
            fields=[
                ('id3', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('st_id', models.CharField(max_length=32, verbose_name='学生学号')),
                ('co_st_id', models.CharField(max_length=32, verbose_name='综测编号')),
                ('st_name', models.CharField(default='', max_length=32, verbose_name='学生姓名')),
                ('st_class', models.CharField(max_length=32, verbose_name='学生班级')),
                ('su_picture', models.CharField(max_length=50, verbose_name='图片索引')),
                ('cl3_grade', models.FloatField(verbose_name='三级成绩')),
                ('co_st_verify', models.BooleanField(verbose_name='审核类型')),
            ],
            options={
                'db_table': 'class3_grade',
            },
        ),
        migrations.CreateModel(
            name='Cotest_Standard',
            fields=[
                ('co_st_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='综测编号')),
                ('co_st_name', models.CharField(max_length=32, verbose_name='综测名称')),
                ('co_st_type', models.IntegerField(verbose_name='综测类型')),
                ('co_st_verify', models.BooleanField(verbose_name='审核种类')),
            ],
            options={
                'db_table': 'cotest_standard',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生学号')),
                ('st_class', models.CharField(max_length=32, verbose_name='学生班级')),
                ('st_name', models.CharField(max_length=32, verbose_name='学生姓名')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Supporting_Materials',
            fields=[
                ('su_ma_id', models.AutoField(primary_key=True, serialize=False, verbose_name='材料编号')),
                ('co_st_id', models.CharField(max_length=32, verbose_name='综测编号')),
                ('te_id', models.CharField(max_length=32, verbose_name='教师工号')),
                ('su_ma_index', models.CharField(max_length=50, verbose_name='文件索引')),
            ],
            options={
                'db_table': 'supporting_materials',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('te_id', models.AutoField(primary_key=True, serialize=False, verbose_name='教师工号')),
                ('te_class', models.IntegerField(verbose_name='教师等级')),
                ('te_name', models.CharField(max_length=32, verbose_name='教师姓名')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户账号')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('type', models.IntegerField(verbose_name='用户身份')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
